version: "3.1"
services:

  redis:
    image: redis:alpine
    container_name: pa-dev-redis
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: pa-dev-mysql
    working_dir: /application
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=92TsoUIdq41h
      - MYSQL_DATABASE=padevdbdb
      - MYSQL_USER=padevuser
      - MYSQL_PASSWORD=8uh4JlELNjkh
    ports:
      - "3306:3306"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: pa-dev-nginx
    working_dir: /application
    volumes:
      - ./src:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - app-network

  app:
    build: docker/php-fpm
    container_name: pa-dev-app
    working_dir: /application
    volumes:
      - ./src:/application
      - ./docker/php-fpm/php.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
